
#ifndef __VISUAL_TUNNING__
#define __VISUAL_TUNNING__

#define ACCEPTED_VALUE_FOR_EDGE 50
#define IGNORABLE_EDGE_DENSITY 0.275
#define PIXELS_PER_STEP 12
#define REGION_LENGTH 45
#define REGION_HEIGHT 45
#define REGION_WIDTH 45

#endif 
